/**
 * Seed dataset for Lattice — a career / skill graph.
 * Sized for CognoDB free tier while remaining realistic enough to explore.
 */

export const skills = [
  { id: "sk-python", name: "Python", category: "Languages", demand: 95 },
  { id: "sk-js", name: "JavaScript", category: "Languages", demand: 94 },
  { id: "sk-ts", name: "TypeScript", category: "Languages", demand: 92 },
  { id: "sk-sql", name: "SQL", category: "Languages", demand: 90 },
  { id: "sk-go", name: "Go", category: "Languages", demand: 78 },
  { id: "sk-java", name: "Java", category: "Languages", demand: 82 },
  { id: "sk-react", name: "React", category: "Frontend", demand: 91 },
  { id: "sk-css", name: "CSS / Design Systems", category: "Frontend", demand: 80 },
  { id: "sk-a11y", name: "Accessibility", category: "Frontend", demand: 72 },
  { id: "sk-node", name: "Node.js", category: "Backend", demand: 88 },
  { id: "sk-apis", name: "API Design", category: "Backend", demand: 86 },
  { id: "sk-db", name: "Database Modeling", category: "Backend", demand: 84 },
  { id: "sk-graphs", name: "Graph Databases", category: "Backend", demand: 68 },
  { id: "sk-dist", name: "Distributed Systems", category: "Backend", demand: 81 },
  { id: "sk-k8s", name: "Kubernetes", category: "Infrastructure", demand: 83 },
  { id: "sk-aws", name: "AWS", category: "Infrastructure", demand: 89 },
  { id: "sk-ci", name: "CI/CD", category: "Infrastructure", demand: 85 },
  { id: "sk-obs", name: "Observability", category: "Infrastructure", demand: 79 },
  { id: "sk-security", name: "Application Security", category: "Infrastructure", demand: 77 },
  { id: "sk-ml", name: "Machine Learning", category: "Data & AI", demand: 87 },
  { id: "sk-stats", name: "Statistics", category: "Data & AI", demand: 80 },
  { id: "sk-etl", name: "Data Pipelines", category: "Data & AI", demand: 84 },
  { id: "sk-viz", name: "Data Visualization", category: "Data & AI", demand: 75 },
  { id: "sk-llm", name: "LLM Applications", category: "Data & AI", demand: 88 },
  { id: "sk-prompt", name: "Prompt Engineering", category: "Data & AI", demand: 76 },
  { id: "sk-rag", name: "RAG Systems", category: "Data & AI", demand: 82 },
  { id: "sk-pm", name: "Product Strategy", category: "Product", demand: 86 },
  { id: "sk-user", name: "User Research", category: "Product", demand: 78 },
  { id: "sk-roadmap", name: "Roadmapping", category: "Product", demand: 81 },
  { id: "sk-metrics", name: "Product Metrics", category: "Product", demand: 83 },
  { id: "sk-figma", name: "Figma", category: "Design", demand: 85 },
  { id: "sk-ux", name: "UX Writing", category: "Design", demand: 70 },
  { id: "sk-proto", name: "Prototyping", category: "Design", demand: 79 },
  { id: "sk-research", name: "Design Research", category: "Design", demand: 74 },
  { id: "sk-comms", name: "Stakeholder Communication", category: "Leadership", demand: 88 },
  { id: "sk-hire", name: "Hiring", category: "Leadership", demand: 76 },
  { id: "sk-mentor", name: "Mentorship", category: "Leadership", demand: 80 },
  { id: "sk-systems", name: "Systems Thinking", category: "Leadership", demand: 84 },
  { id: "sk-story", name: "Technical Writing", category: "Communication", demand: 73 },
  { id: "sk-present", name: "Presentation", category: "Communication", demand: 77 },
  { id: "sk-experiment", name: "Experiment Design", category: "Product", demand: 79 },
  { id: "sk-mobile", name: "Mobile Development", category: "Frontend", demand: 74 },
  { id: "sk-testing", name: "Automated Testing", category: "Backend", demand: 82 },
  { id: "sk-perf", name: "Performance Tuning", category: "Backend", demand: 76 },
  { id: "sk-eval", name: "Model Evaluation", category: "Data & AI", demand: 81 },
];

export const roles = [
  {
    id: "role-fe-jr",
    name: "Junior Frontend Engineer",
    level: "Junior",
    domain: "Engineering",
    description: "Builds UI components and ships product surfaces with mentorship.",
  },
  {
    id: "role-fe",
    name: "Frontend Engineer",
    level: "Mid",
    domain: "Engineering",
    description: "Owns complex client features, design-system quality, and UX polish.",
  },
  {
    id: "role-fe-sr",
    name: "Senior Frontend Engineer",
    level: "Senior",
    domain: "Engineering",
    description: "Sets frontend architecture and mentors across product squads.",
  },
  {
    id: "role-be-jr",
    name: "Junior Backend Engineer",
    level: "Junior",
    domain: "Engineering",
    description: "Implements APIs and data access with guidance from seniors.",
  },
  {
    id: "role-be",
    name: "Backend Engineer",
    level: "Mid",
    domain: "Engineering",
    description: "Designs services, schemas, and reliable API contracts.",
  },
  {
    id: "role-be-sr",
    name: "Senior Backend Engineer",
    level: "Senior",
    domain: "Engineering",
    description: "Leads service architecture, scaling, and operational excellence.",
  },
  {
    id: "role-fs",
    name: "Full-Stack Engineer",
    level: "Mid",
    domain: "Engineering",
    description: "Spans product UI and API layers end to end.",
  },
  {
    id: "role-fs-sr",
    name: "Senior Full-Stack Engineer",
    level: "Senior",
    domain: "Engineering",
    description: "Owns vertical slices and cross-cutting platform concerns.",
  },
  {
    id: "role-devops",
    name: "DevOps Engineer",
    level: "Mid",
    domain: "Engineering",
    description: "Automates delivery pipelines and cloud infrastructure.",
  },
  {
    id: "role-sre",
    name: "Site Reliability Engineer",
    level: "Senior",
    domain: "Engineering",
    description: "Keeps systems reliable through observability and automation.",
  },
  {
    id: "role-sec",
    name: "Security Engineer",
    level: "Senior",
    domain: "Engineering",
    description: "Hardens applications and reviews threat models.",
  },
  {
    id: "role-de",
    name: "Data Engineer",
    level: "Mid",
    domain: "Data",
    description: "Builds pipelines that turn raw events into trustworthy datasets.",
  },
  {
    id: "role-de-sr",
    name: "Senior Data Engineer",
    level: "Senior",
    domain: "Data",
    description: "Owns warehouse architecture and data platform reliability.",
  },
  {
    id: "role-da",
    name: "Data Analyst",
    level: "Mid",
    domain: "Data",
    description: "Answers business questions with SQL, metrics, and visuals.",
  },
  {
    id: "role-ds",
    name: "Data Scientist",
    level: "Mid",
    domain: "Data",
    description: "Models uncertainty and extracts signal from product data.",
  },
  {
    id: "role-ds-sr",
    name: "Senior Data Scientist",
    level: "Senior",
    domain: "Data",
    description: "Leads modeling strategy and partners with product on experiments.",
  },
  {
    id: "role-mle",
    name: "ML Engineer",
    level: "Mid",
    domain: "Data",
    description: "Productionizes models into maintainable services.",
  },
  {
    id: "role-mle-sr",
    name: "Senior ML Engineer",
    level: "Senior",
    domain: "Data",
    description: "Designs ML platforms and evaluation loops at scale.",
  },
  {
    id: "role-ai",
    name: "AI Engineer",
    level: "Mid",
    domain: "Data",
    description: "Ships LLM features: prompts, retrieval, evaluation, guardrails.",
  },
  {
    id: "role-ai-sr",
    name: "Senior AI Engineer",
    level: "Senior",
    domain: "Data",
    description: "Architects agentic systems and retrieval platforms.",
  },
  {
    id: "role-pm-a",
    name: "Associate Product Manager",
    level: "Junior",
    domain: "Product",
    description: "Supports discovery, specs, and release coordination.",
  },
  {
    id: "role-pm",
    name: "Product Manager",
    level: "Mid",
    domain: "Product",
    description: "Owns outcomes for a product area with engineering & design.",
  },
  {
    id: "role-pm-sr",
    name: "Senior Product Manager",
    level: "Senior",
    domain: "Product",
    description: "Sets strategy across a portfolio and mentors PMs.",
  },
  {
    id: "role-tpm",
    name: "Technical Product Manager",
    level: "Senior",
    domain: "Product",
    description: "Bridges deep technical systems with product bets.",
  },
  {
    id: "role-ux",
    name: "UX Designer",
    level: "Mid",
    domain: "Design",
    description: "Crafts flows, prototypes, and interaction quality.",
  },
  {
    id: "role-ux-sr",
    name: "Senior UX Designer",
    level: "Senior",
    domain: "Design",
    description: "Owns end-to-end experience quality across products.",
  },
  {
    id: "role-uxr",
    name: "UX Researcher",
    level: "Mid",
    domain: "Design",
    description: "Runs studies that de-risk product decisions.",
  },
  {
    id: "role-em",
    name: "Engineering Manager",
    level: "Lead",
    domain: "Leadership",
    description: "Builds teams, coaching loops, and delivery systems.",
  },
  {
    id: "role-tl",
    name: "Tech Lead",
    level: "Lead",
    domain: "Leadership",
    description: "Guides technical direction while still close to the code.",
  },
  {
    id: "role-staff",
    name: "Staff Engineer",
    level: "Staff",
    domain: "Leadership",
    description: "Solves org-wide technical problems with influence, not authority.",
  },
];

/** roleId -> [{ skillId, importance }] */
export const roleSkills: Record<string, Array<{ skillId: string; importance: string }>> = {
  "role-fe-jr": [
    { skillId: "sk-js", importance: "core" },
    { skillId: "sk-react", importance: "core" },
    { skillId: "sk-css", importance: "strong" },
    { skillId: "sk-ts", importance: "helpful" },
  ],
  "role-fe": [
    { skillId: "sk-js", importance: "core" },
    { skillId: "sk-ts", importance: "core" },
    { skillId: "sk-react", importance: "core" },
    { skillId: "sk-css", importance: "strong" },
    { skillId: "sk-a11y", importance: "strong" },
    { skillId: "sk-testing", importance: "helpful" },
  ],
  "role-fe-sr": [
    { skillId: "sk-ts", importance: "core" },
    { skillId: "sk-react", importance: "core" },
    { skillId: "sk-css", importance: "strong" },
    { skillId: "sk-a11y", importance: "strong" },
    { skillId: "sk-perf", importance: "strong" },
    { skillId: "sk-mentor", importance: "strong" },
    { skillId: "sk-systems", importance: "helpful" },
  ],
  "role-be-jr": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-sql", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-node", importance: "helpful" },
  ],
  "role-be": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-node", importance: "strong" },
    { skillId: "sk-sql", importance: "core" },
    { skillId: "sk-apis", importance: "core" },
    { skillId: "sk-db", importance: "strong" },
    { skillId: "sk-testing", importance: "strong" },
  ],
  "role-be-sr": [
    { skillId: "sk-apis", importance: "core" },
    { skillId: "sk-db", importance: "core" },
    { skillId: "sk-dist", importance: "core" },
    { skillId: "sk-sql", importance: "strong" },
    { skillId: "sk-obs", importance: "strong" },
    { skillId: "sk-go", importance: "helpful" },
    { skillId: "sk-graphs", importance: "helpful" },
  ],
  "role-fs": [
    { skillId: "sk-ts", importance: "core" },
    { skillId: "sk-react", importance: "core" },
    { skillId: "sk-node", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-sql", importance: "strong" },
  ],
  "role-fs-sr": [
    { skillId: "sk-ts", importance: "core" },
    { skillId: "sk-react", importance: "strong" },
    { skillId: "sk-node", importance: "core" },
    { skillId: "sk-apis", importance: "core" },
    { skillId: "sk-db", importance: "strong" },
    { skillId: "sk-systems", importance: "strong" },
    { skillId: "sk-mentor", importance: "helpful" },
  ],
  "role-devops": [
    { skillId: "sk-aws", importance: "core" },
    { skillId: "sk-ci", importance: "core" },
    { skillId: "sk-k8s", importance: "strong" },
    { skillId: "sk-python", importance: "helpful" },
    { skillId: "sk-obs", importance: "strong" },
  ],
  "role-sre": [
    { skillId: "sk-k8s", importance: "core" },
    { skillId: "sk-obs", importance: "core" },
    { skillId: "sk-dist", importance: "core" },
    { skillId: "sk-aws", importance: "strong" },
    { skillId: "sk-python", importance: "strong" },
    { skillId: "sk-perf", importance: "strong" },
  ],
  "role-sec": [
    { skillId: "sk-security", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-aws", importance: "strong" },
    { skillId: "sk-python", importance: "helpful" },
    { skillId: "sk-story", importance: "helpful" },
  ],
  "role-de": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-sql", importance: "core" },
    { skillId: "sk-etl", importance: "core" },
    { skillId: "sk-aws", importance: "strong" },
    { skillId: "sk-db", importance: "strong" },
  ],
  "role-de-sr": [
    { skillId: "sk-etl", importance: "core" },
    { skillId: "sk-db", importance: "core" },
    { skillId: "sk-sql", importance: "core" },
    { skillId: "sk-dist", importance: "strong" },
    { skillId: "sk-python", importance: "strong" },
    { skillId: "sk-aws", importance: "strong" },
  ],
  "role-da": [
    { skillId: "sk-sql", importance: "core" },
    { skillId: "sk-viz", importance: "core" },
    { skillId: "sk-stats", importance: "strong" },
    { skillId: "sk-present", importance: "strong" },
    { skillId: "sk-metrics", importance: "strong" },
  ],
  "role-ds": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-stats", importance: "core" },
    { skillId: "sk-ml", importance: "core" },
    { skillId: "sk-sql", importance: "strong" },
    { skillId: "sk-viz", importance: "helpful" },
    { skillId: "sk-experiment", importance: "strong" },
  ],
  "role-ds-sr": [
    { skillId: "sk-ml", importance: "core" },
    { skillId: "sk-stats", importance: "core" },
    { skillId: "sk-experiment", importance: "core" },
    { skillId: "sk-python", importance: "strong" },
    { skillId: "sk-comms", importance: "strong" },
    { skillId: "sk-present", importance: "strong" },
  ],
  "role-mle": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-ml", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-etl", importance: "strong" },
    { skillId: "sk-aws", importance: "strong" },
    { skillId: "sk-testing", importance: "helpful" },
  ],
  "role-mle-sr": [
    { skillId: "sk-ml", importance: "core" },
    { skillId: "sk-dist", importance: "core" },
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-obs", importance: "strong" },
    { skillId: "sk-systems", importance: "strong" },
  ],
  "role-ai": [
    { skillId: "sk-python", importance: "core" },
    { skillId: "sk-llm", importance: "core" },
    { skillId: "sk-rag", importance: "core" },
    { skillId: "sk-prompt", importance: "strong" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-ts", importance: "helpful" },
  ],
  "role-ai-sr": [
    { skillId: "sk-llm", importance: "core" },
    { skillId: "sk-rag", importance: "core" },
    { skillId: "sk-graphs", importance: "strong" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-systems", importance: "core" },
    { skillId: "sk-eval", importance: "strong" },
  ],
  "role-pm-a": [
    { skillId: "sk-user", importance: "core" },
    { skillId: "sk-comms", importance: "strong" },
    { skillId: "sk-roadmap", importance: "helpful" },
    { skillId: "sk-metrics", importance: "helpful" },
  ],
  "role-pm": [
    { skillId: "sk-pm", importance: "core" },
    { skillId: "sk-roadmap", importance: "core" },
    { skillId: "sk-user", importance: "strong" },
    { skillId: "sk-metrics", importance: "core" },
    { skillId: "sk-comms", importance: "strong" },
    { skillId: "sk-experiment", importance: "strong" },
  ],
  "role-pm-sr": [
    { skillId: "sk-pm", importance: "core" },
    { skillId: "sk-roadmap", importance: "core" },
    { skillId: "sk-comms", importance: "core" },
    { skillId: "sk-metrics", importance: "strong" },
    { skillId: "sk-systems", importance: "strong" },
    { skillId: "sk-present", importance: "strong" },
  ],
  "role-tpm": [
    { skillId: "sk-pm", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-systems", importance: "core" },
    { skillId: "sk-roadmap", importance: "strong" },
    { skillId: "sk-story", importance: "strong" },
    { skillId: "sk-sql", importance: "helpful" },
  ],
  "role-ux": [
    { skillId: "sk-figma", importance: "core" },
    { skillId: "sk-proto", importance: "core" },
    { skillId: "sk-user", importance: "strong" },
    { skillId: "sk-a11y", importance: "strong" },
    { skillId: "sk-ux", importance: "helpful" },
  ],
  "role-ux-sr": [
    { skillId: "sk-figma", importance: "core" },
    { skillId: "sk-proto", importance: "core" },
    { skillId: "sk-research", importance: "strong" },
    { skillId: "sk-systems", importance: "strong" },
    { skillId: "sk-comms", importance: "strong" },
    { skillId: "sk-a11y", importance: "strong" },
  ],
  "role-uxr": [
    { skillId: "sk-research", importance: "core" },
    { skillId: "sk-user", importance: "core" },
    { skillId: "sk-present", importance: "strong" },
    { skillId: "sk-story", importance: "strong" },
    { skillId: "sk-stats", importance: "helpful" },
  ],
  "role-em": [
    { skillId: "sk-hire", importance: "core" },
    { skillId: "sk-mentor", importance: "core" },
    { skillId: "sk-comms", importance: "core" },
    { skillId: "sk-systems", importance: "strong" },
    { skillId: "sk-roadmap", importance: "helpful" },
  ],
  "role-tl": [
    { skillId: "sk-systems", importance: "core" },
    { skillId: "sk-mentor", importance: "core" },
    { skillId: "sk-apis", importance: "strong" },
    { skillId: "sk-comms", importance: "strong" },
    { skillId: "sk-story", importance: "helpful" },
  ],
  "role-staff": [
    { skillId: "sk-systems", importance: "core" },
    { skillId: "sk-dist", importance: "core" },
    { skillId: "sk-comms", importance: "core" },
    { skillId: "sk-mentor", importance: "strong" },
    { skillId: "sk-present", importance: "strong" },
  ],
};

// Fix: role-ai-sr references sk-eval which doesn't exist. Add it or remove.
// I'll add sk-eval to skills list in seed script merge, or fix roleSkills.
// Let me fix by adding the skill in seed.ts when writing, or update data now.

export const skillRelations: Array<{ from: string; to: string; strength: number }> = [
  { from: "sk-js", to: "sk-ts", strength: 0.95 },
  { from: "sk-ts", to: "sk-react", strength: 0.9 },
  { from: "sk-python", to: "sk-ml", strength: 0.85 },
  { from: "sk-ml", to: "sk-llm", strength: 0.8 },
  { from: "sk-llm", to: "sk-rag", strength: 0.92 },
  { from: "sk-rag", to: "sk-graphs", strength: 0.7 },
  { from: "sk-sql", to: "sk-db", strength: 0.88 },
  { from: "sk-db", to: "sk-graphs", strength: 0.65 },
  { from: "sk-apis", to: "sk-dist", strength: 0.75 },
  { from: "sk-aws", to: "sk-k8s", strength: 0.8 },
  { from: "sk-k8s", to: "sk-obs", strength: 0.78 },
  { from: "sk-user", to: "sk-research", strength: 0.85 },
  { from: "sk-metrics", to: "sk-experiment", strength: 0.82 },
  { from: "sk-pm", to: "sk-roadmap", strength: 0.9 },
  { from: "sk-mentor", to: "sk-hire", strength: 0.7 },
  { from: "sk-etl", to: "sk-ml", strength: 0.72 },
  { from: "sk-react", to: "sk-a11y", strength: 0.68 },
  { from: "sk-stats", to: "sk-experiment", strength: 0.8 },
];

export const transitions: Array<{
  from: string;
  to: string;
  frequency: string;
  difficulty: string;
}> = [
  { from: "role-fe-jr", to: "role-fe", frequency: "very common", difficulty: "low" },
  { from: "role-fe", to: "role-fe-sr", frequency: "common", difficulty: "medium" },
  { from: "role-fe", to: "role-fs", frequency: "common", difficulty: "medium" },
  { from: "role-fe-sr", to: "role-tl", frequency: "common", difficulty: "medium" },
  { from: "role-fe-sr", to: "role-em", frequency: "common", difficulty: "medium" },
  { from: "role-be-jr", to: "role-be", frequency: "very common", difficulty: "low" },
  { from: "role-be", to: "role-be-sr", frequency: "common", difficulty: "medium" },
  { from: "role-be", to: "role-fs", frequency: "common", difficulty: "medium" },
  { from: "role-be", to: "role-de", frequency: "occasional", difficulty: "medium" },
  { from: "role-be-sr", to: "role-tl", frequency: "common", difficulty: "medium" },
  { from: "role-be-sr", to: "role-sre", frequency: "occasional", difficulty: "medium" },
  { from: "role-be-sr", to: "role-staff", frequency: "occasional", difficulty: "high" },
  { from: "role-be-sr", to: "role-tpm", frequency: "occasional", difficulty: "medium" },
  { from: "role-fs", to: "role-fs-sr", frequency: "common", difficulty: "medium" },
  { from: "role-fs", to: "role-ai", frequency: "emerging", difficulty: "medium" },
  { from: "role-fs-sr", to: "role-tl", frequency: "common", difficulty: "medium" },
  { from: "role-fs-sr", to: "role-ai-sr", frequency: "emerging", difficulty: "high" },
  { from: "role-devops", to: "role-sre", frequency: "common", difficulty: "medium" },
  { from: "role-devops", to: "role-sec", frequency: "occasional", difficulty: "medium" },
  { from: "role-be", to: "role-devops", frequency: "occasional", difficulty: "medium" },
  { from: "role-de", to: "role-de-sr", frequency: "common", difficulty: "medium" },
  { from: "role-de", to: "role-mle", frequency: "common", difficulty: "medium" },
  { from: "role-de-sr", to: "role-staff", frequency: "occasional", difficulty: "high" },
  { from: "role-da", to: "role-ds", frequency: "common", difficulty: "medium" },
  { from: "role-da", to: "role-pm", frequency: "occasional", difficulty: "medium" },
  { from: "role-ds", to: "role-ds-sr", frequency: "common", difficulty: "medium" },
  { from: "role-ds", to: "role-mle", frequency: "common", difficulty: "medium" },
  { from: "role-ds", to: "role-ai", frequency: "emerging", difficulty: "medium" },
  { from: "role-mle", to: "role-mle-sr", frequency: "common", difficulty: "medium" },
  { from: "role-mle", to: "role-ai", frequency: "emerging", difficulty: "low" },
  { from: "role-ai", to: "role-ai-sr", frequency: "emerging", difficulty: "medium" },
  { from: "role-mle-sr", to: "role-ai-sr", frequency: "emerging", difficulty: "low" },
  { from: "role-ai-sr", to: "role-staff", frequency: "occasional", difficulty: "high" },
  { from: "role-pm-a", to: "role-pm", frequency: "very common", difficulty: "low" },
  { from: "role-pm", to: "role-pm-sr", frequency: "common", difficulty: "medium" },
  { from: "role-pm", to: "role-tpm", frequency: "occasional", difficulty: "medium" },
  { from: "role-ux", to: "role-ux-sr", frequency: "common", difficulty: "medium" },
  { from: "role-ux", to: "role-pm", frequency: "occasional", difficulty: "medium" },
  { from: "role-uxr", to: "role-ux-sr", frequency: "occasional", difficulty: "medium" },
  { from: "role-uxr", to: "role-pm", frequency: "occasional", difficulty: "medium" },
  { from: "role-tl", to: "role-em", frequency: "common", difficulty: "medium" },
  { from: "role-tl", to: "role-staff", frequency: "common", difficulty: "high" },
  { from: "role-be-jr", to: "role-da", frequency: "occasional", difficulty: "medium" },
  { from: "role-fe", to: "role-ux", frequency: "rare", difficulty: "high" },
];

export const companies = [
  { id: "co-north", name: "Northwind Labs", industry: "SaaS", size: "200-500" },
  { id: "co-harbor", name: "Harbor Analytics", industry: "Data Platform", size: "50-200" },
  { id: "co-cedar", name: "Cedar Health", industry: "Healthtech", size: "500-1000" },
  { id: "co-orbit", name: "Orbit Pay", industry: "Fintech", size: "200-500" },
  { id: "co-moss", name: "Moss Media", industry: "Consumer", size: "50-200" },
  { id: "co-quartz", name: "Quartz Robotics", industry: "Hardware + AI", size: "200-500" },
  { id: "co-folio", name: "Folio Education", industry: "Edtech", size: "50-200" },
  { id: "co-signal", name: "Signal Graph", industry: "Developer Tools", size: "20-50" },
  { id: "co-atlas", name: "Atlas Mobility", industry: "Logistics", size: "1000+" },
  { id: "co-lumen", name: "Lumen Design Co", industry: "Agency", size: "20-50" },
];

export const people: Array<{
  id: string;
  name: string;
  headline: string;
  companyId: string;
  roles: Array<{ roleId: string; years: number; order: number }>;
  skillIds: string[];
}> = [
  {
    id: "p-aria",
    name: "Aria Chen",
    headline: "Frontend → Full-stack pathfinder",
    companyId: "co-north",
    roles: [
      { roleId: "role-fe-jr", years: 2, order: 1 },
      { roleId: "role-fe", years: 3, order: 2 },
      { roleId: "role-fs", years: 2, order: 3 },
    ],
    skillIds: ["sk-ts", "sk-react", "sk-node", "sk-apis", "sk-css"],
  },
  {
    id: "p-devon",
    name: "Devon Okonkwo",
    headline: "Backend engineer exploring ML systems",
    companyId: "co-harbor",
    roles: [
      { roleId: "role-be", years: 4, order: 1 },
      { roleId: "role-de", years: 2, order: 2 },
      { roleId: "role-mle", years: 1, order: 3 },
    ],
    skillIds: ["sk-python", "sk-sql", "sk-etl", "sk-ml", "sk-apis"],
  },
  {
    id: "p-mira",
    name: "Mira Patel",
    headline: "Analyst turned product manager",
    companyId: "co-orbit",
    roles: [
      { roleId: "role-da", years: 3, order: 1 },
      { roleId: "role-pm", years: 3, order: 2 },
    ],
    skillIds: ["sk-sql", "sk-metrics", "sk-pm", "sk-comms", "sk-experiment"],
  },
  {
    id: "p-jonas",
    name: "Jonas Berg",
    headline: "SRE focused on observability culture",
    companyId: "co-atlas",
    roles: [
      { roleId: "role-be", years: 3, order: 1 },
      { roleId: "role-devops", years: 2, order: 2 },
      { roleId: "role-sre", years: 3, order: 3 },
    ],
    skillIds: ["sk-k8s", "sk-obs", "sk-aws", "sk-python", "sk-dist"],
  },
  {
    id: "p-leila",
    name: "Leila Haddad",
    headline: "Designer who partners deeply with PMs",
    companyId: "co-lumen",
    roles: [
      { roleId: "role-ux", years: 4, order: 1 },
      { roleId: "role-ux-sr", years: 2, order: 2 },
    ],
    skillIds: ["sk-figma", "sk-proto", "sk-user", "sk-a11y", "sk-comms"],
  },
  {
    id: "p-sam",
    name: "Sam Rivera",
    headline: "Data scientist shipping LLM features",
    companyId: "co-signal",
    roles: [
      { roleId: "role-ds", years: 3, order: 1 },
      { roleId: "role-ai", years: 2, order: 2 },
    ],
    skillIds: ["sk-python", "sk-ml", "sk-llm", "sk-rag", "sk-prompt"],
  },
  {
    id: "p-nina",
    name: "Nina Volkov",
    headline: "Tech lead bridging platform and product",
    companyId: "co-cedar",
    roles: [
      { roleId: "role-be-sr", years: 4, order: 1 },
      { roleId: "role-tl", years: 3, order: 2 },
    ],
    skillIds: ["sk-apis", "sk-dist", "sk-systems", "sk-mentor", "sk-comms"],
  },
  {
    id: "p-omar",
    name: "Omar Farouk",
    headline: "PM with a technical systems lens",
    companyId: "co-quartz",
    roles: [
      { roleId: "role-be", years: 2, order: 1 },
      { roleId: "role-pm", years: 2, order: 2 },
      { roleId: "role-tpm", years: 2, order: 3 },
    ],
    skillIds: ["sk-pm", "sk-apis", "sk-systems", "sk-roadmap", "sk-story"],
  },
  {
    id: "p-priya",
    name: "Priya Nair",
    headline: "ML engineer moving into AI platform work",
    companyId: "co-harbor",
    roles: [
      { roleId: "role-mle", years: 3, order: 1 },
      { roleId: "role-ai-sr", years: 1, order: 2 },
    ],
    skillIds: ["sk-ml", "sk-llm", "sk-rag", "sk-python", "sk-systems"],
  },
  {
    id: "p-chris",
    name: "Chris Yamamoto",
    headline: "Full-stack engineer mentoring juniors",
    companyId: "co-folio",
    roles: [
      { roleId: "role-fs", years: 3, order: 1 },
      { roleId: "role-fs-sr", years: 2, order: 2 },
    ],
    skillIds: ["sk-ts", "sk-react", "sk-node", "sk-db", "sk-mentor"],
  },
  {
    id: "p-elena",
    name: "Elena Rossi",
    headline: "Researcher informing product bets",
    companyId: "co-moss",
    roles: [
      { roleId: "role-uxr", years: 4, order: 1 },
      { roleId: "role-pm", years: 1, order: 2 },
    ],
    skillIds: ["sk-research", "sk-user", "sk-present", "sk-pm", "sk-story"],
  },
  {
    id: "p-kai",
    name: "Kai Thompson",
    headline: "Security-minded platform engineer",
    companyId: "co-orbit",
    roles: [
      { roleId: "role-devops", years: 3, order: 1 },
      { roleId: "role-sec", years: 2, order: 2 },
    ],
    skillIds: ["sk-security", "sk-aws", "sk-k8s", "sk-apis", "sk-python"],
  },
];
